### ISSUE TITLE
Legal usage

### ISSUE THREAD

**Issue by donlk** [daviddoria/PointSetProcessing#7]
Hi David,
Excellent toolset you got here with convenient build integration. My question is, what are the terms of usages for your code? Can you provide a license file, or leaving it out was intentional?

Thanks in advance,
Andrew

**Comment by daviddoria** [comment]
Hi Andrew,

You're welcome to use any code I've written for any purpose. That said, I can not be held responsible for any code that was contributed by others or dependencies that may not share the same permissions. Short story - it's fine with me, but I'm not sure who else you would need it to be fine with :)

David

**Comment by donlk** [comment]
The reason why i'm asking is because the lack of license in a project implies that you retain all your rights to your code, and you allow no derivations or modifications for any 3rdparty whatsoever.
https://help.github.com/articles/open-source-licensing/

I see this is was not your intention. As you implemented VTK submodules and you aimed for seamless integration with their build process, i suggest you choose their license for your project as well.
Its BSD 3, i think you can choose this directly from your project settings, no need to import it from somewhere else.

**Comment by daviddoria** [comment]
I added a BSD3 License.txt file - let me know if that is sufficient.

**Comment by donlk** [comment]
Excellent. Thank you very much!

**Comment by daviddoria** [comment]
I would love to hear about where it gets used if you end up using it!
